# Generated by Django 3.1.7 on 2021-03-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='bill_date',
            new_name='bill_generated_on',
        ),
    ]
