# Generated by Django 3.1.7 on 2021-03-24 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('report', '0002_auto_20210324_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='patient_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
    ]
